# Vectors: Goal of this notebook is to get full understanding of vectors. 
- Mathematical Definition: 
  - Scalar
  - Vector 
  - Matrix 

#### How vectors are used in Machine learning. 
#### Vector encodings for different type of data
  - NLP 
    1. Words
    2. Sentences 
  - Numbers 
  - Images  

In [1]:
import pandas as pd
import numpy as np

In [4]:
# Load the csv file for the house price data
house_price_df = pd.read_csv('../git_data/kc_house_data.csv')
house_price_df.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7        1180              0   
1      7242     2.0           0     0  ...      7        2170            400   
2     10000     1.0           0     0  ...      6         770              0   
3      5000     1.0           0     0  ...      7        1050            910   
4      8080     1.0           0     0  ...      8        1680              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   

   sqft_lot15  
0        5650  
1        7639  
2        8062  
3        5000  
4        7503  

[5 rows x 21 columns]

In [30]:
# This is a numpy row vector
# print(house_price_df[["bedrooms", "sqft_lot"]].values[:3,:])
# This is a numpy column vector
print(house_price_df[["bedrooms", "sqft_lot"]].values.T[:2,:1])

[[   3]
 [5650]]


### NLP Vectorization
- Prepositions 
  - A preposition usually precedes a noun or a pronoun. Here is a list of commonly used prepositions: above, across, against, along, among, around, at, before, behind, below, beneath, beside, between, by, down, from, in, into, near, of, off, on, to, toward, under, upon, with and within '''

- Conjuctions 
    1. Because	She usually eats at home, because she likes cooking.
    2. Although	Although he speaks seldom, he says meaningful words.

In [43]:
from sklearn.feature_extraction.text import CountVectorizer
# Example to show bag of words and frequency of words in a given document. 
words = ['martin', 'marthin','luther','marthin marthin luther']
cv = CountVectorizer()
# Compressed Sparse Row Matrixs. 
X = cv.fit_transform(words)
# print(type(X)) 
X = X.toarray()

print(X)


[[0 0 1]
 [0 1 0]
 [1 0 0]
 [1 2 0]]


In [42]:
cv.vocabulary_.keys()
# sorted(cv.vocabulary_.keys())
# print(X)

dict_keys(['martin', 'marthin', 'luther'])

#### TF-IDF 


In [46]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
transformed = tfidf.fit_transform(words)
import pandas as pd
df = pd.DataFrame(transformed[0].T.todense(),
    	index=tfidf.get_feature_names(), columns=["TF-IDF"])
df = df.sort_values('TF-IDF', ascending=False)
df

/home/uncomment/.local/lib/python3.8/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


TF-IDF
martin      1.0
luther      0.0
marthin     0.0